/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-11-06 12:26:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class analysisdetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>Script Analyser</title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("     <link href=\"https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-sb-admin-2/3.3.7+1/css/sb-admin-2.css\" rel=\"stylesheet\"> \r\n");
      out.write("     <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">  \r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Lobster\" rel=\"stylesheet\">\r\n");
      out.write("   <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js\"></script>\r\n");
      out.write("     \r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <!--  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-sb-admin-2/3.3.7+1/js/sb-admin-2.js\"></script>-->\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/metisMenu/2.7.0/metisMenu.js\"></script>\r\n");
      out.write("    <script language=\"javascript\" type=\"text/javascript\" src=\"viz.js\"></script>\r\n");
      out.write("    <script language=\"javascript\" type=\"text/javascript\" src=\"site.js\"> </script>\r\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("  <script src=\"http://malsup.github.com/jquery.form.js\"></script>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("    .h{\r\n");
      out.write("        max-height: 100px;\r\n");
      out.write("        overflow-y:scroll;\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write(" \r\n");
      out.write("       <script>\r\n");
      out.write("       var arrResponse;\r\n");
      out.write("       window.onload = function() {\r\n");
      out.write("    \tarrResponse=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(";\r\n");
      out.write("    \t   var obj=arrResponse;\r\n");
      out.write("    \t  // document.getElementById(\"hd\").innerHTML = \"Fileconten\"t;\r\n");
      out.write("    \t      \t //  document.getElementById(\"hd\").sytle.color = \"red\";\r\n");
      out.write("\r\n");
      out.write("    \t   document.getElementById(\"hd\").innerHTML = \"FileContent\";\r\n");
      out.write("\r\n");
      out.write("    \t   document.getElementById(\"inputTextToSave\").innerHTML = arrResponse.fileContent;\r\n");
      out.write("            var mainUL=document.getElementById(\"c\");\r\n");
      out.write("           // alert( obj.codeBlocks.length);\r\n");
      out.write("           // var text=document.getElementById(\"inputTextToSave\");\r\n");
      out.write("          //  text.document.createTextNode(arrResponse.fileContent);\r\n");
      out.write("       \r\n");
      out.write("           for(i=0;i<arrResponse.codeBlocks.length;i++)\r\n");
      out.write("        \t{\r\n");
      out.write("        \t   var para = document.createElement(\"li\");\r\n");
      out.write("        \t   \r\n");
      out.write("        \t   //var dtext=\"<a href=# onclick=source(\"+i+\")>Code Block &nbsp\"+ arrResponse.codeBlocks[i].cbid +\"\"+ arrResponse.codeBlocks[i].lineno +\" </a>\";\r\n");
      out.write("        \t   var a = document.createElement('a');\r\n");
      out.write("        \t   var linkText = document.createTextNode(\"Code Block \"+ arrResponse.codeBlocks[i].cbid +\"  [\"+ arrResponse.codeBlocks[i].lineno +\"  ]\");\r\n");
      out.write("        \t   a.appendChild(linkText);\r\n");
      out.write("        \t   a.setAttribute('onclick','source('+i+')');\r\n");
      out.write("        \t   a.href = \"#\";\r\n");
      out.write("        \t   para.appendChild(a);\r\n");
      out.write("        \t   mainUL.appendChild(para);\r\n");
      out.write("        \t\r\n");
      out.write("        \t}\r\n");
      out.write("    \t };\r\n");
      out.write("    \t function UpdateGraphviz(index) {\r\n");
      out.write("    \t\t  var svg_div=document.getElementById(\"graphviz_svg_div1\");\r\n");
      out.write("    \t        // alert(\"hello\");\r\n");
      out.write("    \t\t    var data = arrResponse.codeBlocks[index].graph;\r\n");
      out.write("    \t\t    // Generate the Visualization of the Graph into \"svg\".\r\n");
      out.write("    \t\t    var svg = Viz(data, \"svg\");\r\n");
      out.write("    \t\t    svg_div.innerHTML=\"<hr>\"+svg;\r\n");
      out.write("    \t\t    document.getElementById(\"graphviz_svg_div\").innerHTML=\"\";\r\n");
      out.write("    \t\t  }\r\n");
      out.write("    \t function getSVG(){\r\n");
      out.write("    \t\t var e = document.createElement('script');\r\n");
      out.write("       \t\te.setAttribute('src', 'https://nytimes.github.io/svg-crowbar/svg-crowbar.js'); \r\n");
      out.write("       \t\te.setAttribute('class', 'svg-crowbar');\r\n");
      out.write("       \t\tdocument.body.appendChild(e);\r\n");
      out.write("    \t }\r\n");
      out.write("    \r\n");
      out.write(" \t   \r\n");
      out.write("    \t function comGraph() {\r\n");
      out.write("    \t\t \r\n");
      out.write("    \t\t document.getElementById('graphviz_svg_div1').style.display = 'none';\r\n");
      out.write("    \t\t    document.getElementById('graphviz_svg_div').style.display = 'Block';\r\n");
      out.write("      \t\t  var svg_div=document.getElementById(\"graphviz_svg_div\");\r\n");
      out.write("      \t         //alert(\"hello\");\r\n");
      out.write("      \t      var data = arrResponse.completeGraph;\r\n");
      out.write("      \t    document.getElementById(\"hd\").innerHTML = \"FileContent\";\r\n");
      out.write("      \t    document.getElementById(\"inputTextToSave\").innerHTML = arrResponse.fileContent;\r\n");
      out.write("      \t\t    // Generate the Visualization of the Graph into \"svg\".\r\n");
      out.write("      \t\t   // alert(data);\r\n");
      out.write("      \t\t    var svg = Viz(data, \"svg\");\r\n");
      out.write("      \t\t    svg_div.innerHTML=\"<hr>\"+svg;\r\n");
      out.write("      \t\t// add these lines in showdata()\r\n");
      out.write("      \t   \t\tvar srctables=\"\",tgttables=\"\",stdalntables=\"\";\r\n");
      out.write("      \t   \t\t      \t  for (i = 0; i < arrResponse.srctableList.length; i++)                             \r\n");
      out.write("      \t   \t\t          { \r\n");
      out.write("      \t   \t\t          srctables += \"&nbsp &nbsp &nbsp\"+arrResponse.srctableList[i]+ \"<br>\";\r\n");
      out.write("      \t   \t\t          }                                \r\n");
      out.write("      \t   \t\t         document.getElementById(\"sourcetables\").innerHTML = srctables;\r\n");
      out.write("      \t   \t\t   \r\n");
      out.write("      \t   \t\t//target tables\r\n");
      out.write("      \t   \t\t\t\tfor (i = 0; i < arrResponse.tartableList.length; i++)                             \r\n");
      out.write("      \t   \t\t          { \r\n");
      out.write("      \t   \t\t          tgttables += \"&nbsp &nbsp &nbsp\"+arrResponse.tartableList[i]+ \"<br>\";\r\n");
      out.write("      \t   \t\t          }                                \r\n");
      out.write("      \t   \t\t         document.getElementById(\"targettables\").innerHTML = tgttables;\r\n");
      out.write("      \t   \t\t        document.getElementById(\"stdalonetables\").innerHTML = stdalntables;\r\n");
      out.write("      \t   \t\t   document.getElementById(\"graphviz_svg_div1\").innerHTML=\"\";\r\n");
      out.write("      \t\t  }\r\n");
      out.write("       \t \r\n");
      out.write("       \t \r\n");
      out.write("      \r\n");
      out.write("    \t \r\n");
      out.write("   \r\n");
      out.write("    \t    function showData()\r\n");
      out.write("    \t     {\r\n");
      out.write("    \t    \tvar arrResponse=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(";\r\n");
      out.write("   \t    POST('showdata', {\"a\":\"aa\"}); \r\n");
      out.write("   \t    \r\n");
      out.write("    \t     }\r\n");
      out.write("    \t  \r\n");
      out.write("function source(index)\r\n");
      out.write("{\r\n");
      out.write("\t//$(\".graphviz_svg_div\").hide();\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.getElementById('graphviz_svg_div').style.display = 'none';\r\n");
      out.write("    document.getElementById('graphviz_svg_div1').style.display = 'Block';\r\n");
      out.write("\t//arrResponse.codeBlocks[index].cbid.sytle.color=\"red\";\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tdocument.getElementById(\"hd\").innerHTML = \"CodeBlock\"+ arrResponse.codeBlocks[index].cbid;\r\n");
      out.write("\t\t\t var i,j,k,l,srctables=\"\",tgttables=\"\",stdalntables=\"\",graphdata=\"\";\r\n");
      out.write("             \r\n");
      out.write("             UpdateGraphviz(index);\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar temp=\"\";\r\n");
      out.write("             \r\n");
      out.write("             //System.out.println(arrResponse.codeBlocks[index].query.length);\r\n");
      out.write(" \t\t\tfor ( i=0;i< arrResponse.codeBlocks[index].query.length; i++){\r\n");
      out.write(" \t\t\ttemp = temp + arrResponse.codeBlocks[index].query[i]+ '\\n';\r\n");
      out.write(" \t\t\t}\r\n");
      out.write(" \t\t\t//alert(temp);\r\n");
      out.write("             //document.getElementById(\"inputTextToSave\").innerHTML = arrResponse.codeBlocks[index].query;\r\n");
      out.write("             document.getElementById(\"inputTextToSave\").innerHTML = temp; \r\n");
      out.write("            \r\n");
      out.write("            //alert(obj.codeBlocks[index].query);\r\n");
      out.write("             \r\n");
      out.write("            //alert(obj.codeBlocks[index].dbSrcTables.lsength);\r\n");
      out.write("              //source tables\r\n");
      out.write("              for (i = 0; i < arrResponse.codeBlocks[index].dbSrcTables.length; i++)                             \r\n");
      out.write("               { \r\n");
      out.write("               srctables += \"&nbsp &nbsp &nbsp\"+arrResponse.codeBlocks[index].dbSrcTables[i]+ \"<br>\";\r\n");
      out.write("               }                                \r\n");
      out.write("              document.getElementById(\"sourcetables\").innerHTML = srctables;\r\n");
      out.write("        \r\n");
      out.write("\t//target tables\r\n");
      out.write("             for (j = 0; j < arrResponse.codeBlocks[index].dbTargetTables.length; j++)                             \r\n");
      out.write("              { \r\n");
      out.write("               if((arrResponse.codeBlocks[index].dbTargetTables)!=\"\"){\r\n");
      out.write("\r\n");
      out.write("                  tgttables += \"&nbsp &nbsp &nbsp\"+arrResponse.codeBlocks[index].dbTargetTables[j]+\"&nbsp &nbsp &nbsp &nbsp\"+ \"<span class=\\\"label label-success \\\">\"+arrResponse.codeBlocks[index].action +\"</span><br>\";\r\n");
      out.write("               }\r\n");
      out.write("              \r\n");
      out.write("              }\r\n");
      out.write("             document.getElementById(\"targettables\").innerHTML = tgttables;\r\n");
      out.write("\t\r\n");
      out.write("             document.getElementById(\"stdalonetables\").innerHTML = stdalntables;\r\n");
      out.write("             //standalone tables\r\n");
      out.write("             for (k = 0; k < arrResponse.codeBlocks[index].dbStAloneTables.length; k++)                             \r\n");
      out.write("              { \r\n");
      out.write("\r\n");
      out.write("               if((arrResponse.codeBlocks[index].dbStAloneTables)!=\"\"){\r\n");
      out.write("\r\n");
      out.write("              stdalntables += \"&nbsp &nbsp &nbsp\"+arrResponse.codeBlocks[index].dbStAloneTables[k]+\"&nbsp &nbsp &nbsp &nbsp <span class=\\\"label label-success \\\">\"+arrResponse.codeBlocks[index].action +\"</span><br>\";\r\n");
      out.write("              }                                                         \r\n");
      out.write("             document.getElementById(\"stdalonetables\").innerHTML = stdalntables;\r\n");
      out.write("\r\n");
      out.write("         }\r\n");
      out.write("           \r\n");
      out.write("\t}\r\n");
      out.write("// custom form method\r\n");
      out.write("\r\n");
      out.write("function POST(path, params, method) {\r\n");
      out.write("    method = method || \"post\"; // Set method to post by default if not specified.\r\n");
      out.write("\r\n");
      out.write("    // The rest of this code assumes you are not using a library.\r\n");
      out.write("    // It can be made less wordy if you use one.\r\n");
      out.write("    var form = document.createElement(\"form\");\r\n");
      out.write("    form.setAttribute(\"method\", method);\r\n");
      out.write("    form.setAttribute(\"action\", path);\r\n");
      out.write("\r\n");
      out.write("    for(var key in params) {\r\n");
      out.write("        if(params.hasOwnProperty(key)) {\r\n");
      out.write("            var hiddenField = document.createElement(\"input\");\r\n");
      out.write("            hiddenField.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("            hiddenField.setAttribute(\"name\", key);\r\n");
      out.write("            hiddenField.setAttribute(\"value\", params[key]);\r\n");
      out.write("\t\t\t//alert( key);\r\n");
      out.write("\r\n");
      out.write("//alert( params[key]);\r\n");
      out.write("            form.appendChild(hiddenField);\r\n");
      out.write("         }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    document.body.appendChild(form);\r\n");
      out.write("    form.submit();\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("           \r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Navigation -->\r\n");
      out.write("\r\n");
      out.write("             <label class=\"navbar-brand\" href=\"home.html\" style=\"font-family: 'Lobster', cursive; margin-top:0px;margin-left:0px;font-size:35px; color:#fff;height=20px\">\r\n");
      out.write("                <span style=\"color:#000000;\">Script Analyzer</span>\r\n");
      out.write("            </label>\r\n");
      out.write("            <div class=\"navbar-default sidebar\" role=\"navigation\">\r\n");
      out.write("               <div class=\"sidebar-nav navbar-collapse\">\r\n");
      out.write("                    <ul class=\"nav\" id=\"side-menu\" >\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\" style=\"color:#F44336;\"><i class=\"fa fa-circle-o fa-fw\"></i>Code Blocks<span class=\"fa arrow\"></span></a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level collapse in h\" id=\"c\">\r\n");
      out.write("\t                            \r\n");
      out.write("                            </ul>\r\n");
      out.write("             </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\" style=\"color:#01579B\"><i class=\"fa fa-circle-o fa-fw\"></i>Source Tables<span class=\"fa arrow\">                             </span></a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level collapse in h\" id=\"sourcetables\">\r\n");
      out.write("                      \r\n");
      out.write("                     \r\n");
      out.write("                \r\n");
      out.write("                            </ul>                            \r\n");
      out.write("                            <!-- /.nav-second-level -->\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\" style=\"color:#1B5E20\"><i class=\"fa fa-circle-o fa-fw\"></i>Target Tables<span class=\"fa arrow\">                             </span></a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level collapse in h\" id=\"targettables\"><li id=\"d\"></li>\r\n");
      out.write("                            </ul>                            \r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\" style=\"color:#BF360C;\"><i class=\"fa fa-circle-o fa-fw\"></i>Table Created/Deleted<span class=\"fa arrow\"></span></a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level collapse in h\" id=\"stdalonetables\">\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <br><br>\r\n");
      out.write("           <center>\r\n");
      out.write("           <button id=\"generate_btn1\" class=\"btn btn-primary btn-outline btn-block\"  disabled style=\"font-size: 100%\" onclick=\"comGraph()\">name=\"Show Diagram(Complete)\"\r\n");
      out.write("           </button>\r\n");
      out.write("           </center>  \r\n");
      out.write("            <br>\r\n");
      out.write("            <form action=\"/scriptanalyzer\" method=\"post\" id=\"analyzedifffile\">\r\n");
      out.write("            <center>\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary btn-outline btn-block\">Analyze Different File</button>\r\n");
      out.write("            \r\n");
      out.write("           <!--   <center>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"index.jsp\" class=\"btn btn-primary btn-outline btn-lg\">Analyze\r\n");
      out.write("\t\t\t\t\t\t\t\t\tDifferenttt File</a>\r\n");
      out.write("\t\t\t\t\t\t</center> <br>-->\r\n");
      out.write("\t\t\t\t\t      </center>      \r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t                  \r\n");
      out.write("               \t\t\t<center><br>\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary btn-outline btn-block\" value=\"data\" onclick=\"showData()\">Consolidated Table List</button> \r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary btn-outline btn-block\" onclick=\"getSVG()\">export image</button> \r\n");
      out.write("                         <!--  <a href=\"../displayTable.jsp\">Consolidated Table List</a>-->\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- /.nav-second-level -->\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.sidebar-collapse -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.navbar-static-side -->\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"page-wrapper\"><br>\r\n");
      out.write("        <div id=\"hd\" class=\"row btn-primary\" ></div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"form-group\">           \r\n");
      out.write("            <textarea id=\"inputTextToSave\" rows=\"10 \" class=\"form-control\" readonly> </textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> \r\n");
      out.write("               <!--   <button id=\"generate_btn\" class=\"btn btn-primary btn-outline btn-lg\" name=\"Show Diagram(Code Block Wise)\" disabled style=\"font-size: 100%\"><b>Loading...</b></button>\r\n");
      out.write("                &nbsp;&nbsp;\r\n");
      out.write("                <button id=\"generate_btn1\" class=\"btn btn-primary btn-outline btn-lg\" name=\"Show Diagram(Complete)\" disabled style=\"font-size: 100%\"><b>Loading...</b>\r\n");
      out.write("                </button> \r\n");
      out.write("             <textarea id=\"graphviz_data\" rows=\"5\" cols=\"80\" width=\"100%\" wrap=\"off\" hidden ></textarea>\r\n");
      out.write("            <textarea id=\"graphviz_data1\" rows=\"5\" cols=\"80\" width=\"100%\" wrap=\"off\" hidden></textarea>\r\n");
      out.write("           \t <script>\r\n");
      out.write("            //complete diagram \r\n");
      out.write("\t\t\t\r\n");
      out.write("            </script>-->\r\n");
      out.write("    \r\n");
      out.write("        <!-- /#page-wrapper --> \r\n");
      out.write("        <div id=\"graphviz_svg_div\">\r\n");
      out.write("  <!-- Target for dynamic svg generation -->\r\n");
      out.write("        </div>\r\n");
      out.write("    <div id=\"graphviz_svg_div1\">\r\n");
      out.write("  <!-- Target for dynamic svg generation -->\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /#wrapper -->\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
